# Generated by Django 3.2.6 on 2021-09-14 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminId', models.CharField(max_length=50, null=True)),
                ('Fname', models.CharField(max_length=50, null=True)),
                ('Lname', models.CharField(max_length=50, null=True)),
                ('Pass', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerId', models.CharField(max_length=50, null=True)),
                ('phoneNum', models.IntegerField()),
                ('Fname', models.CharField(max_length=50, null=True)),
                ('Lname', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeId', models.CharField(max_length=50, null=True)),
                ('Lname', models.CharField(max_length=50, null=True)),
                ('Fname', models.CharField(max_length=50, null=True)),
                ('Uname', models.CharField(max_length=50, null=True)),
                ('phoneNum', models.IntegerField()),
                ('Pass', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodId', models.CharField(max_length=200, null=True)),
                ('Name', models.CharField(max_length=200, null=True)),
                ('Quantity', models.IntegerField()),
                ('unitPrice', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menuId', models.CharField(max_length=200, null=True)),
                ('Price', models.IntegerField()),
                ('foodId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.food')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.customer')),
            ],
        ),
        migrations.CreateModel(
            name='orderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderId', models.CharField(max_length=50, null=True)),
                ('Quantity', models.IntegerField()),
                ('unitPrice', models.IntegerField()),
                ('foodId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.food')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentId', models.CharField(max_length=50, null=True)),
                ('amount', models.IntegerField()),
                ('paymentType', models.CharField(max_length=50, null=True)),
                ('customerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.customer')),
                ('orderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.orderitem')),
            ],
        ),
        migrations.DeleteModel(
            name='Features',
        ),
        migrations.AddField(
            model_name='order',
            name='orderId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.orderitem'),
        ),
        migrations.AddField(
            model_name='employee',
            name='orderId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.orderitem'),
        ),
        migrations.AddField(
            model_name='customer',
            name='foodId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.food'),
        ),
        migrations.AddField(
            model_name='admin',
            name='menuId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.menu'),
        ),
    ]
