# Generated by Django 3.2.6 on 2021-10-20 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('adminId', models.AutoField(primary_key=True, serialize=False)),
                ('Fname', models.CharField(max_length=50, null=True)),
                ('Lname', models.CharField(max_length=50, null=True)),
                ('Uname', models.CharField(max_length=50, null=True)),
                ('Pass', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customerId', models.AutoField(primary_key=True, serialize=False)),
                ('phoneNum', models.IntegerField()),
                ('Fname', models.CharField(max_length=50, null=True)),
                ('Lname', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('foodId', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50, null=True)),
                ('Quantity', models.IntegerField()),
                ('unitPrice', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='orderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderId', models.CharField(max_length=50, null=True)),
                ('Quantity', models.IntegerField()),
                ('unitPrice', models.IntegerField()),
                ('foodId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.food')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentId', models.CharField(max_length=50, null=True)),
                ('amount', models.IntegerField()),
                ('paymentType', models.CharField(max_length=50, null=True)),
                ('customerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.customer')),
                ('orderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.orderitem')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.customer')),
                ('orderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.orderitem')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('menuId', models.AutoField(primary_key=True, serialize=False)),
                ('Price', models.IntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.customer')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.food')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeId', models.CharField(max_length=50, null=True)),
                ('Lname', models.CharField(max_length=50, null=True)),
                ('Fname', models.CharField(max_length=50, null=True)),
                ('Uname', models.CharField(max_length=50, null=True)),
                ('phoneNum', models.IntegerField()),
                ('Pass', models.CharField(max_length=50, null=True)),
                ('orderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.orderitem')),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.customer')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.food'),
        ),
    ]
