# Generated by Django 3.2.9 on 2022-03-03 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('resId', models.AutoField(primary_key=True, serialize=False)),
                ('availRooms', models.CharField(max_length=50, null=True)),
                ('title', models.CharField(max_length=50, null=True)),
                ('resDate', models.DateField()),
                ('resTime', models.TimeField()),
            ],
        ),
    ]
