# Generated by Django 3.2.9 on 2022-03-20 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('resId', models.AutoField(primary_key=True, serialize=False)),
                ('availRooms', models.CharField(max_length=50, null=True)),
                ('title', models.CharField(max_length=50, null=True)),
                ('resDate', models.DateField(blank=True, null=True)),
                ('resTime', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('bookId', models.AutoField(primary_key=True, serialize=False)),
                ('bRoom', models.IntegerField()),
                ('numBook', models.IntegerField()),
                ('availRooms', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.reservation')),
            ],
        ),
    ]
