# Generated by Django 3.2.9 on 2022-03-03 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='resDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='resTime',
            field=models.TimeField(null=True),
        ),
    ]
