# Generated by Django 3.2.6 on 2022-02-23 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.RemoveField(
            model_name='email',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='orderId',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='food',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='orderId',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='foodId',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='customerId',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='orderId',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Email',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Food',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='orderItem',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
