# Generated by Django 4.0.2 on 2022-03-24 02:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0003_alter_reservation_resdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('lastname', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=50, null=True)),
                ('phone_number', models.IntegerField()),
                ('profpic', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('street', models.CharField(max_length=50, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
